'use server';

/**
 * @fileOverview Refines a study schedule based on user feedback and preferences.
 *
 * - refineStudySchedule -  A function that accepts user feedback and refines the existing study schedule.
 * - RefineStudyScheduleInput - The input type for the refineStudySchedule function.
 * - RefineStudyScheduleOutput - The return type for the refineStudySchedule function.
 */

import {type Genkit} from 'genkit';
import {z} from 'genkit';
import {ai as defaultAi} from '@/ai/genkit';

const RefineStudyScheduleInputSchema = z.object({
  initialSchedule: z
    .string()
    .describe('The initial study schedule generated by the AI.'),
  feedback: z
    .string()
    .describe(
      'User feedback on the initial schedule, including specific topics to focus on, preferred study times, and any other constraints.'
    ),
});
export type RefineStudyScheduleInput = z.infer<typeof RefineStudyScheduleInputSchema>;

const RefineStudyScheduleOutputSchema = z.object({
  refinedSchedule: z
    .string()
    .describe('The refined study schedule, incorporating user feedback.'),
});
export type RefineStudyScheduleOutput = z.infer<typeof RefineStudyScheduleOutputSchema>;

export async function refineStudySchedule(
  input: RefineStudyScheduleInput,
  ai: Genkit = defaultAi
): Promise<RefineStudyScheduleOutput> {
  const refineStudyScheduleFlow = ai.defineFlow(
    {
      name: 'refineStudyScheduleFlow',
      inputSchema: RefineStudyScheduleInputSchema,
      outputSchema: RefineStudyScheduleOutputSchema,
    },
    async input => {
      const prompt = ai.definePrompt({
        name: 'refineStudySchedulePrompt',
        input: {schema: RefineStudyScheduleInputSchema},
        output: {schema: RefineStudyScheduleOutputSchema},
        prompt: `You are an AI assistant designed to refine study schedules based on user feedback.

  The user has provided an initial study schedule and some feedback on how to improve it. Your goal is to generate a new, improved study schedule that takes into account the user's feedback.

  Initial Study Schedule:
  {{initialSchedule}}

  User Feedback:
  {{feedback}}

  Refined Study Schedule:`,
      });
      const {output} = await prompt(input);
      return output!;
    }
  );
  return refineStudyScheduleFlow(input);
}
