'use server';

/**
 * @fileOverview Refines a study schedule based on user feedback and preferences.
 *
 * - refineStudySchedule -  A function that accepts user feedback and refines the existing study schedule.
 * - RefineStudyScheduleInput - The input type for the refineStudySchedule function.
 * - RefineStudyScheduleOutput - The return type for the refineStudySchedule function.
 */

import {z} from 'genkit';
import {ai} from '@/ai/genkit';

const RefineStudyScheduleInputSchema = z.object({
  initialSchedule: z
    .string()
    .describe('The initial descriptive study schedule generated by the AI.'),
  initialScheduleTable: z
    .string()
    .describe('The initial table-formatted study schedule generated by the AI.'),
  feedback: z
    .string()
    .describe(
      'User feedback on the initial schedule, including specific topics to focus on, preferred study times, and any other constraints.'
    ),
});
export type RefineStudyScheduleInput = z.infer<typeof RefineStudyScheduleInputSchema>;

const RefineStudyScheduleOutputSchema = z.object({
  refinedSchedule: z
    .string()
    .describe('The refined descriptive study schedule in Markdown, incorporating user feedback.'),
  refinedScheduleTable: z
    .string()
    .describe('The refined table-formatted study schedule in a Markdown table, incorporating user feedback.'),
});
export type RefineStudyScheduleOutput = z.infer<typeof RefineStudyScheduleOutputSchema>;


const refineStudyScheduleFlow = ai.defineFlow(
  {
    name: 'refineStudyScheduleFlow',
    inputSchema: RefineStudyScheduleInputSchema,
    outputSchema: RefineStudyScheduleOutputSchema,
  },
  async input => {
    const prompt = ai.definePrompt({
      name: 'refineStudySchedulePrompt',
      input: {schema: RefineStudyScheduleInputSchema},
      output: {schema: RefineStudyScheduleOutputSchema},
      prompt: `You are an AI assistant designed to refine study schedules based on user feedback.

The user has provided an initial study schedule (in both descriptive and table formats) and some feedback on how to improve it. Your goal is to generate a new, improved schedule in both formats that takes into account the user's feedback.

Initial Descriptive Schedule:
{{{initialSchedule}}}

Initial Table Schedule:
{{{initialScheduleTable}}}

User Feedback:
{{{feedback}}}

Based on the feedback, generate the 'refinedSchedule' (descriptive Markdown) and 'refinedScheduleTable' (Markdown table) fields in your output.`,
    });
    const {output} = await prompt(input);
    return output!;
  }
);

export async function refineStudySchedule(
  input: RefineStudyScheduleInput,
): Promise<RefineStudyScheduleOutput> {
  return refineStudyScheduleFlow(input);
}
