'use client';

import { useState, useTransition } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import type { z } from 'zod';
import { format } from 'date-fns';
import { Calendar as CalendarIcon, Loader2, Download, Edit, Sparkles, Redo } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';


import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { createScheduleAction, refineScheduleAction } from '@/app/actions';
import { formSchema } from '@/lib/schema';

type ViewState = 'form' | 'loading' | 'schedule';

export default function StudyPlannerClient() {
  const [view, setView] = useState<ViewState>('form');
  const [schedule, setSchedule] = useState<string>('');
  const [scheduleTable, setScheduleTable] = useState<string>('');
  const [refinementFeedback, setRefinementFeedback] = useState('');
  const [isRefining, startRefiningTransition] = useTransition();
  const { toast } = useToast();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      topics: '',
      commitments: 'Work: Mon-Fri 9am-5pm. Class: Tue/Thu 1pm-2:30pm',
      availability: 'Weekdays 6pm-10pm, Weekends 10am-6pm',
      studyStyle: 'A mix of both',
      sessionLength: '1 hour',
      understanding: 'Have some knowledge',
      goals: '',
      additionalInfo: 'I learn best by doing practice problems.',
      blockoutDays: 'Friday evenings',
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setView('loading');
    const result = await createScheduleAction(values);
    if (result.success && result.schedule && result.scheduleTable) {
      setSchedule(result.schedule);
      setScheduleTable(result.scheduleTable);
      setView('schedule');
    } else {
      toast({
        variant: 'destructive',
        title: 'Error Generating Schedule',
        description: result.error,
      });
      setView('form');
    }
  }

  function handlePrint() {
    window.print();
  }

  function handleStartOver() {
    form.reset({
      topics: '',
      commitments: 'Work: Mon-Fri 9am-5pm. Class: Tue/Thu 1pm-2:30pm',
      availability: 'Weekdays 6pm-10pm, Weekends 10am-6pm',
      studyStyle: 'A mix of both',
      sessionLength: '1 hour',
      understanding: 'Have some knowledge',
      goals: '',
      additionalInfo: 'I learn best by doing practice problems.',
      blockoutDays: 'Friday evenings',
    });
    setSchedule('');
    setScheduleTable('');
    setView('form');
  }
  

  function handleRefine() {
    startRefiningTransition(async () => {
      const result = await refineScheduleAction(schedule, scheduleTable, refinementFeedback);
      if (result.success && result.schedule && result.scheduleTable) {
        setSchedule(result.schedule);
        setScheduleTable(result.scheduleTable);
        setRefinementFeedback('');
        toast({
          title: 'Schedule Refined!',
          description: 'Your study plan has been updated with your feedback.',
        });
      } else {
        toast({
          variant: 'destructive',
          title: 'Error Refining Schedule',
          description: result.error,
        });
      }
    });
  }

  if (view === 'loading') {
    return (
      <Card className="flex flex-col items-center justify-center p-12 text-center animate-pulse">
        <Sparkles className="h-12 w-12 text-primary mb-4" />
        <CardTitle className="text-2xl">Crafting Your Plan...</CardTitle>
        <CardDescription>Our AI is building your personalized study schedule. This might take a moment.</CardDescription>
      </Card>
    );
  }

  if (view === 'schedule') {
    return (
      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle className="font-headline text-2xl md:text-3xl">Your Personalized Study Plan</CardTitle>
            <CardDescription>Here is the schedule generated by our AI. You can switch between views and refine it below.</CardDescription>
          </CardHeader>
          <CardContent>
            <Tabs defaultValue="description">
              <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="description">Descriptive Plan</TabsTrigger>
                <TabsTrigger value="table">Table View</TabsTrigger>
              </TabsList>
              <TabsContent value="description" className="mt-4">
                 <div className="printable-area prose dark:prose-invert max-w-none rounded-lg border bg-muted/30 p-6">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{schedule}</ReactMarkdown>
                 </div>
              </TabsContent>
              <TabsContent value="table" className="mt-4">
                 <div className="printable-area prose dark:prose-invert max-w-none rounded-lg border bg-muted/30 p-6">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{scheduleTable}</ReactMarkdown>
                 </div>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>

        <Card className="no-print">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Edit className="h-6 w-6" />
              Refine Your Schedule
            </CardTitle>
            <CardDescription>
              Is something not quite right? Tell the AI what you'd like to change. 
              (e.g., "Make my Wednesday sessions shorter", "Focus more on Topic X on weekends")
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <Textarea
                placeholder="Enter your feedback here..."
                value={refinementFeedback}
                onChange={(e) => setRefinementFeedback(e.target.value)}
                rows={4}
              />
              <Button onClick={handleRefine} disabled={isRefining || !refinementFeedback.trim()}>
                {isRefining && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Refine Schedule
              </Button>
            </div>
          </CardContent>
        </Card>

        <div className="flex flex-col sm:flex-row gap-4 no-print">
          <Button onClick={handlePrint} className="w-full sm:w-auto"><Download className="mr-2 h-4 w-4" />Download PDF</Button>
          <Button onClick={handleStartOver} variant="outline" className="w-full sm:w-auto"><Redo className="mr-2 h-4 w-4" />Start Over</Button>
        </div>
      </div>
    );
  }

  return (
    <Card className="shadow-lg">
      <CardHeader>
        <CardTitle className="font-headline text-2xl">Tell Us About Your Study Needs</CardTitle>
        <CardDescription>The more details you provide, the better your personalized plan will be.</CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <FormField
                control={form.control}
                name="topics"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Topics/Subjects</FormLabel>
                    <FormControl>
                      <Textarea placeholder="e.g., Calculus, European History, React Hooks" {...field} rows={4} />
                    </FormControl>
                    <FormDescription>List all subjects or topics you need to study.</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="goals"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Main Goal</FormLabel>
                    <FormControl>
                      <Textarea placeholder="e.g., Pass the final exam, Get an A grade, Build a project" {...field} rows={4} />
                    </FormControl>
                     <FormDescription>What do you want to achieve with this plan?</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <FormField
                  control={form.control}
                  name="examDate"
                  render={({ field }) => (
                    <FormItem className="flex flex-col">
                      <FormLabel>Exam or Deadline Date</FormLabel>
                      <Popover>
                        <PopoverTrigger asChild>
                          <FormControl>
                            <Button
                              variant={"outline"}
                              className={cn("w-full pl-3 text-left font-normal", !field.value && "text-muted-foreground")}
                            >
                              {field.value ? format(field.value, "PPP") : <span>Pick a date</span>}
                              <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                            </Button>
                          </FormControl>
                        </PopoverTrigger>
                        <PopoverContent className="w-auto p-0" align="start">
                          <Calendar mode="single" selected={field.value} onSelect={field.onChange} initialFocus />
                        </PopoverContent>
                      </Popover>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                    control={form.control}
                    name="understanding"
                    render={({ field }) => (
                      <FormItem className="space-y-3">
                        <FormLabel>Current Understanding of Topics</FormLabel>
                        <FormControl>
                          <RadioGroup onValueChange={field.onChange} defaultValue={field.value} className="flex flex-col space-y-1">
                            <FormItem className="flex items-center space-x-3 space-y-0">
                              <FormControl><RadioGroupItem value="Just starting" /></FormControl>
                              <FormLabel className="font-normal">Just starting (Beginner)</FormLabel>
                            </FormItem>
                            <FormItem className="flex items-center space-x-3 space-y-0">
                              <FormControl><RadioGroupItem value="Have some knowledge" /></FormControl>
                              <FormLabel className="font-normal">Have some knowledge (Intermediate)</FormLabel>
                            </FormItem>
                             <FormItem className="flex items-center space-x-3 space-y-0">
                              <FormControl><RadioGroupItem value="Fairly confident" /></FormControl>
                              <FormLabel className="font-normal">Fairly confident (Advanced)</FormLabel>
                             </FormItem>
                          </RadioGroup>
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
            </div>
            
             <FormField
                control={form.control}
                name="availability"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>General Weekly Availability</FormLabel>
                    <FormControl>
                      <Textarea placeholder="e.g., Weekdays 6pm-10pm, Weekends 10am-6pm" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="commitments"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Fixed Commitments (Job, Classes, etc.)</FormLabel>
                    <FormControl>
                      <Textarea placeholder="e.g., Work: Mon-Fri 9am-5pm. Math Class: Tue/Thu 1pm-2:30pm" {...field} />
                    </FormControl>
                    <FormDescription>List any recurring events that take up your time.</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
               <FormField
                control={form.control}
                name="studyStyle"
                render={({ field }) => (
                  <FormItem className="space-y-3">
                    <FormLabel>Preferred Study Style</FormLabel>
                    <FormControl>
                      <RadioGroup onValueChange={field.onChange} defaultValue={field.value} className="flex flex-col space-y-1">
                        <FormItem className="flex items-center space-x-3 space-y-0">
                          <FormControl><RadioGroupItem value="Long, focused sessions (90+ mins)" /></FormControl>
                          <FormLabel className="font-normal">Long, focused sessions</FormLabel>
                        </FormItem>
                        <FormItem className="flex items-center space-x-3 space-y-0">
                          <FormControl><RadioGroupItem value="Short, frequent breaks (Pomodoro)" /></FormControl>
                          <FormLabel className="font-normal">Short, frequent breaks</FormLabel>
                        </FormItem>
                         <FormItem className="flex items-center space-x-3 space-y-0">
                          <FormControl><RadioGroupItem value="A mix of both" /></FormControl>
                          <FormLabel className="font-normal">A mix of both</FormLabel>
                         </FormItem>
                      </RadioGroup>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
                <FormField
                  control={form.control}
                  name="sessionLength"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Ideal Session Length</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select a preferred duration" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="30 minutes">30 minutes</SelectItem>
                          <SelectItem value="45 minutes">45 minutes</SelectItem>
                          <SelectItem value="1 hour">1 hour</SelectItem>
                          <SelectItem value="1.5 hours">1.5 hours</SelectItem>
                          <SelectItem value="2 hours">2 hours</SelectItem>
                          <SelectItem value="More than 2 hours">More than 2 hours</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
            </div>
            
            <FormField
              control={form.control}
              name="blockoutDays"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Unavailable Times</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g., Friday evenings, Sunday mornings" {...field} />
                  </FormControl>
                  <FormDescription>Any specific days or times you absolutely cannot study?</FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="additionalInfo"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Anything Else?</FormLabel>
                  <FormControl>
                    <Textarea placeholder="e.g., I'm a slow reader, I learn best by doing practice problems..." {...field} />
                  </FormControl>
                  <FormDescription>Any other preferences or constraints for the AI to consider.</FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
            
            <CardFooter className="p-0 pt-8">
              <Button type="submit" size="lg" className="w-full md:w-auto" disabled={form.formState.isSubmitting}>
                {form.formState.isSubmitting ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                   <>
                    <Sparkles className="mr-2 h-4 w-4" />
                    Generate My Study Plan
                  </>
                )}
              </Button>
            </CardFooter>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
